import {
    Observable,
    defer,
    expand,
    filter,
    fromEvent,
    interval,
    map,
    merge,
    timer,
} from "rxjs";

import { flipBit, spawnTarget, tick, togglePause } from "./state";
import { Action, Constants } from "./types";

/** Emits a Tick action at a fixed rate, driving the whole game loop. */
export const tick$: Observable<Action> = interval(Constants.TICK_RATE_MS).pipe(
    map(() => tick),
);

/**
 * Impure only: the raw, filtered keydown-event stream for one key.
 * This function's body only ever touches `document` and the raw
 * KeyboardEvent - it never calls flipBit or any other pure function,
 * so it stays entirely on the impure side.
 */
const keyDownFor = (key: string): Observable<KeyboardEvent> =>
    fromEvent<KeyboardEvent>(document, "keydown").pipe(
        filter(e => e.key === key && !e.repeat),
    );

/**
 * Pure only: turns a digit index into the Action that flips it. Kept
 * as its own named function (rather than inlined in the same map
 * callback as the event stream) so this function's body never
 * touches `document` - it only ever calls the pure flipBit.
 */
const toFlipAction = (index: number): Action => flipBit(index);

/**
 * Builds a stream that emits `flipBit(index)` whenever `key` is
 * pressed. Composed from the two single-purpose pieces above:
 * keyDownFor (impure source) piped into toFlipAction (pure
 * transform) as a separate map stage, instead of one function whose
 * body mixes DOM access and a call into the pure layer.
 */
const keyFlip$ = (key: string, index: number): Observable<Action> =>
    keyDownFor(key).pipe(map(() => toFlipAction(index)));

/** One flip stream per digit (keys "1" to "8"), merged into one stream. */
export const allKeyFlips$: Observable<Action> = defer(() =>
    merge(
        ...Array.from({ length: Constants.DIGIT_COUNT }, (_, i) =>
            keyFlip$(String(i + 1), i),
        ),
    ),
);

/**
 * Impure only: which digit (if any) was clicked, as a raw string
 * index. Touches the DOM event target, but never calls flipBit or
 * any other pure function - the pure conversion happens separately
 * in mouseFlip$ below.
 */
const digitIndexClicks$: Observable<string> = defer(() =>
    fromEvent<MouseEvent>(
        document.querySelector("#svgCanvas") as SVGSVGElement,
        "click",
    ).pipe(
        map(e => (e.target as Element).getAttribute("data-bit-index")),
        filter((index): index is string => index !== null),
    ),
);

/**
 * Clicking a digit box flips that bit too. Listening on #svgCanvas
 * (present from page load) rather than the individual digit rects
 * (created later, inside view.ts) means this works via event
 * delegation no matter when those rects are created.
 */
export const mouseFlip$: Observable<Action> = digitIndexClicks$.pipe(
    map(index => toFlipAction(Number(index))),
);

/**
 * Full Game target sequence: values are random 0-255, and each new
 * target appears a random 1-3 seconds after the previous one (or
 * after the game starts). The randomness happens here, at the
 * Observable "source" boundary, so spawnTarget itself stays a pure
 * function of (value, State) => State regardless of where the value
 * came from.
 */
const randomByte = (): number => Math.floor(Math.random() * 256);
const randomSpawnDelayMs = (): number => 1000 + Math.random() * 2000;
const randomDelay$ = (): Observable<number> => timer(randomSpawnDelayMs());

/**
 * Pure only: turns an already-generated byte value into the Action
 * that spawns it. Kept separate from randomByte() so no single map
 * callback both calls Math.random() and calls spawnTarget() - the
 * random generation and the pure conversion are now two distinct
 * map stages instead of one mixed function body.
 */
const toSpawnAction = (value: number): Action => spawnTarget(value);

export const spawn$: Observable<Action> = defer(randomDelay$).pipe(
    expand(() => randomDelay$()),
    map(() => randomByte()),
    map(toSpawnAction),
);

/**
 * Pressing "p" toggles pause. Wrapped in defer() for the same reason
 * as allKeyFlips$/mouseFlip$: fromEvent touches `document`, so this
 * must not construct until subscription time (matters under vitest).
 */
export const pauseToggle$: Observable<Action> = defer(() =>
    fromEvent<KeyboardEvent>(document, "keydown").pipe(
        filter(e => (e.key === "p" || e.key === "P") && !e.repeat),
        map(() => togglePause),
    ),
);
